# Generated by Django 2.1.7 on 2019-12-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(related_name='_movie_casting_+', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='_movie_directors_+', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='_movie_producers_+', to='persons.Person'),
        ),
    ]
