# Generated by Django 2.1.7 on 2019-12-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('aliases', models.CharField(db_index=True, max_length=255, unique=True)),
                ('movies_as_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromactors', to='movies.Movie')),
                ('movies_as_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons+', to='movies.Movie')),
                ('movies_as_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons+', to='movies.Movie')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
